name: BanAssist
main: com.github.unchama.banassist.BanAssist
version: 0.1.2

commands:
  ignore:
      description: This is a ignore banlist command.
      usage: /<command>
      permission: banassist.ignore
      permission-message: You don't have <permission>
